[package]
name = "mini-fixed32"
version = "0.1.0"
edition = "2021"
authors = ["Eric Wood <eric@ericwood.org>"]
license = "MIT"
keywords = ["fixed", "no-std"]

[features]
defmt = []
fmt = ["float"]
float = []

[dependencies]
defmt = "0.3.8"
